env:
    - TWISTED=Twisted==11.1
    - TWISTED=Twisted==12.0
    - TWISTED=Twisted==12.1
    - TWISTED=Twisted==12.2
    - TWISTED=Twisted==12.3
    - TWISTED=Twisted==13.0
    - TWISTED=Twisted==13.1

language: python

python:
    - 2.6
    - 2.7
    - pypy
# Python 3.3 works, but automated installation and test running are still
# different than on Python 2:
#   - 3.3

install:
    - python setup.py --version
    - pip install -q $TWISTED --use-mirrors
    - python setup.py -q install

script: trial crochet

notifications:
  email: false
